# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: home
    url: /
    weight: 10
  - name: Skills
    parent: home
    url: "#skills"
    weight: 10
  - name: Experience
    parent: home
    url: "#experience"
    weight: 20
  - name: Entrepreneurship
    parent: home
    url: "#entrepreneurship"
    weight: 30
  - name: Courses
    parent: home
    url: "#courses"
    weight: 40
  - name: Awards
    parent: home
    url: "#awards"
    weight: 200

  # Reserve for future feature
  # - name: Tags
  #   identifier: tags
  #   url: "#Tags"
  #   weight: 15
  # - name: Academic
  #   parent: tags
  #   url: tags/academic/
  #   weight: 10

  - name: Events
    url: "events"
    weight: 20
  - name: Posts
    url: "posts"
    weight: 30
  - name: Research
    url: "research"
    weight: 40
  - name: Publications
    url: "publications"
    weight: 50
  - name: Projects
    url: "projects"
    weight: 60
  - name: Teaching
    url: "teaching"
    weight: 70
  - name: Contact
    url: "#contact"
    weight: 80
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 90
